### ISSUE TITLE
mapOutput

### ISSUE THREAD

**Issue by sanchez5674** [ramnathv/rMaps#63]
Hi, 

I install rCharts and try to run a simple example: 

Installing github repo rCharts/master from ramnathv
Downloading master.zip from https://github.com/ramnathv/rCharts/archive/master.zip
Installing package from C:\Users\UCXS920\AppData\Local\Temp\RtmpO213hs/master.zip
Installing rCharts
"C:/PROGRA~1/R/R-31~1.0/bin/x64/R" --vanilla CMD INSTALL  \
  "C:\Users\UCXS920\AppData\Local\Temp\RtmpO213hs\devtools144876b3682\rCharts-master"  \
  --library="C:/Users/UCXS920/Documents/R/win-library/3.1"  \
  --install-tests 
- installing _source_ package 'rCharts' ...
  *\* R
  *\* demo
  *\* inst
  *\* preparing package for lazy loading
  *\* help
  **\* installing help indices
  *\* building package indices
  *\* testing if installed package can be loaded
  **\* arch - i386
  **\* arch - x64
- DONE (rCharts)

library(rCharts)
library(shiny) 

runApp(list(
-   ui = pageWithSidebar(
-     headerPanel("Title"),
-     sidebarPanel("MyApp" ),
-     mainPanel(
-       tabsetPanel(
-         tabPanel("Interactive Map", mapOutput("myChart"))
-       )
-     )
-   ),
-   server = function(input, output){
-     output$myChart <- renderMap({
-       map3 <- Leaflet$new()
-       map3$setView(c(19.4329,- 99.1331), zoom = 8)
-       map3
-     })
-   }
- ))

Everything seems to be fine. However, it gives me the following error which is related to the mapOutput function:

Error in system.file("libraries", lib, package = package) : 
  object 'package' not found

Any ideas? 

By the way, I wrote a similar question to the Shiny-discussion group. 

Thanks for your help. Carlos.

**Comment by imlearningr** [comment]
thank you so much Ramnath! I ran in RStudio the scripts in your comment (with some minor modification according to my data) and was able to produce the app I want in a pop up window. However when I tried to publish the pop window, in R studio, it said he deployment was successful but I got a HTTP 500 error and on the log in https://www.shinyapps.io website I got the following error:

Error in tag("div", list(...)) : could not find function "chartOutput"

I have been researching on this but couldn't find a solution. I saw that in rHighcharts package there is a chartOutput function, but that doesn't seem to work because that function only takes in one parameter. I would really appreciate it if you could give me some thoughts or suggestion.

thanks,
Yi
